/**
 * Generates the service worker after the build. It reads the finished
 * dist folder and writes dist/sw.js with a precache list of every
 * asset, including the lazy lesson chunks, so the whole app works
 * offline after the first load.
 *
 * Navigations go network first with a cache fallback, so a new
 * deployment is picked up as soon as the user is online. Hashed assets
 * are served cache first.
 */

import { createHash } from 'node:crypto';
import { readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const dist = join(root, 'dist');

/** @param {string} dir @returns {string[]} */
function walk(dir) {
  /** @type {string[]} */
  const files = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) files.push(...walk(full));
    else files.push(full);
  }
  return files;
}

let files;
try {
  files = walk(dist)
    .map((f) => `/${relative(dist, f).split('\\').join('/')}`)
    .filter((f) => f !== '/sw.js');
} catch {
  console.error('build-sw. dist folder not found, run vite build first');
  process.exit(1);
}

const assets = ['/', ...files];
const version = createHash('sha256').update(assets.join('\n')).digest('hex').slice(0, 12);

const sw = `// Generated by scripts/build-sw.mjs, do not edit.
const CACHE = 'zahnkurs-${version}';
const ASSETS = ${JSON.stringify(assets)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches
      .open(CACHE)
      .then((cache) => cache.addAll(ASSETS))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;
  // The sync endpoint must always hit the network, never the cache.
  if (url.pathname.startsWith('/api/')) return;

  if (request.mode === 'navigate') {
    // Network first, so a new deployment arrives as soon as possible.
    event.respondWith(
      fetch(request)
        .then((response) => {
          const copy = response.clone();
          caches.open(CACHE).then((cache) => cache.put('/', copy));
          return response;
        })
        .catch(() => caches.match('/').then((cached) => cached ?? Response.error())),
    );
    return;
  }

  // Hashed assets, cache first with a network fallback.
  event.respondWith(
    caches.match(request).then(
      (cached) =>
        cached ??
        fetch(request).then((response) => {
          const copy = response.clone();
          caches.open(CACHE).then((cache) => cache.put(request, copy));
          return response;
        }),
    ),
  );
});
`;

writeFileSync(join(dist, 'sw.js'), sw);
console.log(`Service worker written with ${assets.length} precached files, cache zahnkurs-${version}`);
