/**
 * Content generator. Reads the four markdown files from the content folder,
 * parses and validates them and writes typed data modules into
 * src/content/generated plus a JSON copy for inspection.
 *
 * Run with "npm run generate". The build runs it automatically, so an
 * edited markdown file is picked up on the next deploy. The generated
 * files are committed so the app also builds without running this script.
 *
 * The script fails loudly (non zero exit) on any structural problem.
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { parseGlossaryFile, parseWeekFile } from './parse.mjs';
import { findForbiddenText } from './textrules.mjs';

const root = fileURLToPath(new URL('..', import.meta.url));
const contentDir = `${root}content/`;
const outDir = `${root}src/content/generated/`;

const WEEK_FILES = ['01_kurs_woche1.md', '02_kurs_woche2.md', '03_kurs_woche3.md'];
const GLOSSARY_FILE = '04_glossar_und_spickzettel.md';

/** @param {string} msg */
function fail(msg) {
  console.error(`Content generation failed. ${msg}`);
  process.exit(1);
}

/** @param {number} n */
const pad2 = (n) => String(n).padStart(2, '0');

function main() {
  /** @type {import('../src/content/types.ts').Lesson[]} */
  const lessons = [];
  /** @type {import('../src/content/types.ts').WeekInfo[]} */
  const weeks = [];

  for (const fileName of WEEK_FILES) {
    const text = readFileSync(contentDir + fileName, 'utf8');
    const parsed = parseWeekFile(text, fileName);
    weeks.push({
      week: parsed.week,
      title: parsed.title,
      lessonIds: parsed.lessons.map((l) => l.id),
    });
    lessons.push(...parsed.lessons);
  }

  // Cross file validation. The unit tests check the same rules again
  // against the generated output.
  lessons.sort((a, b) => a.id - b.id);
  if (lessons.length !== 21) fail(`Expected 21 lessons, found ${lessons.length}`);
  lessons.forEach((lesson, i) => {
    if (lesson.id !== i + 1) fail(`Lesson ids must be 1 to 21 without gaps, found ${lesson.id} at position ${i + 1}`);
    if (lesson.day !== lesson.id) fail(`Lesson ${lesson.id} has day ${lesson.day}, expected ${lesson.id}`);
    const expectedQuestions = lesson.isExam ? 20 : 5;
    if (lesson.questions.length !== expectedQuestions) {
      fail(`Lesson ${lesson.id} has ${lesson.questions.length} questions, expected ${expectedQuestions}`);
    }
  });
  if (weeks.map((w) => w.week).join(',') !== '1,2,3') fail('Week files must cover weeks 1, 2 and 3');

  const glossaryText = readFileSync(contentDir + GLOSSARY_FILE, 'utf8');
  const { glossary, cheatsheets } = parseGlossaryFile(glossaryText, GLOSSARY_FILE);
  if (cheatsheets.length !== 5) fail(`Expected 5 cheat sheets, found ${cheatsheets.length}`);

  const seenTerms = new Set();
  for (const group of glossary) {
    for (const entry of group.entries) {
      const key = entry.term.toLowerCase();
      if (seenTerms.has(key)) fail(`Duplicate glossary term "${entry.term}"`);
      seenTerms.add(key);
      for (const ref of entry.lessons) {
        if (ref < 1 || ref > 21) fail(`Glossary term "${entry.term}" references lesson ${ref}`);
      }
    }
  }

  const everything = { weeks, lessons, glossary, cheatsheets };
  const violations = findForbiddenText(everything);
  if (violations.length > 0) {
    const list = violations
      .slice(0, 10)
      .map((v) => `  ${v.path}. "${v.text.slice(0, 80)}"`)
      .join('\n');
    fail(`Forbidden characters (dash, colon or Eszett) in content.\n${list}`);
  }

  // Write output
  mkdirSync(`${outDir}lessons`, { recursive: true });
  /** @param {string} source */
  const header = (source) =>
    `// AUTOGENERATED FILE, do not edit by hand.\n// Generated by scripts/generate.mjs from ${source}\n\n`;

  for (const lesson of lessons) {
    const name = `lesson${pad2(lesson.id)}`;
    const source = WEEK_FILES[lesson.week - 1] ?? 'content';
    const code =
      header(`content/${source}`) +
      `import type { Lesson } from '../../types';\n\n` +
      `const lesson: Lesson = ${JSON.stringify(lesson, null, 2)};\n\n` +
      `export default lesson;\n`;
    writeFileSync(`${outDir}lessons/${name}.ts`, code);
  }

  /** @type {import('../src/content/types.ts').LessonMeta[]} */
  const lessonIndex = lessons.map((l) => ({
    id: l.id,
    title: l.title,
    week: l.week,
    day: l.day,
    durationMinutes: l.durationMinutes,
    metaLine: l.metaLine,
    questionCount: l.questions.length,
    visualCount: l.visuals.length,
    isExam: l.isExam,
  }));

  writeFileSync(
    `${outDir}lessonsIndex.ts`,
    header('content/01_kurs_woche1.md, 02_kurs_woche2.md, 03_kurs_woche3.md') +
      `import type { LessonMeta, WeekInfo } from '../types';\n\n` +
      `export const weeks: WeekInfo[] = ${JSON.stringify(weeks, null, 2)};\n\n` +
      `export const lessonIndex: LessonMeta[] = ${JSON.stringify(lessonIndex, null, 2)};\n`,
  );

  writeFileSync(
    `${outDir}lessons.ts`,
    header('content/01_kurs_woche1.md, 02_kurs_woche2.md, 03_kurs_woche3.md') +
      `import type { Lesson } from '../types';\n\n` +
      lessons.map((l) => `import lesson${pad2(l.id)} from './lessons/lesson${pad2(l.id)}';`).join('\n') +
      `\n\nexport const lessons: Lesson[] = [\n` +
      lessons.map((l) => `  lesson${pad2(l.id)},`).join('\n') +
      `\n];\n`,
  );

  writeFileSync(
    `${outDir}glossary.ts`,
    header(`content/${GLOSSARY_FILE}`) +
      `import type { GlossaryGroup } from '../types';\n\n` +
      `export const glossaryGroups: GlossaryGroup[] = ${JSON.stringify(glossary, null, 2)};\n`,
  );

  writeFileSync(
    `${outDir}cheatsheets.ts`,
    header(`content/${GLOSSARY_FILE}`) +
      `import type { CheatSheet } from '../types';\n\n` +
      `export const cheatsheets: CheatSheet[] = ${JSON.stringify(cheatsheets, null, 2)};\n`,
  );

  writeFileSync(`${outDir}content.json`, `${JSON.stringify(everything, null, 2)}\n`);

  const questionCount = lessons.reduce((sum, l) => sum + l.questions.length, 0);
  const visualCount = lessons.reduce((sum, l) => sum + l.visuals.length, 0);
  const termCount = glossary.reduce((sum, g) => sum + g.entries.length, 0);
  console.log(
    `Generated ${lessons.length} lessons, ${questionCount} questions, ${visualCount} visuals, ` +
      `${termCount} glossary terms, ${cheatsheets.length} cheat sheets.`,
  );
}

main();
